### ISSUE TITLE
There should be an option to filter solution based on solution name, version, description like search.

### ISSUE THREAD

**Issue by nakhtar-ntg** [MscrmTools/MsCrmTools.SolutionComponentsMover#12]
There should be an option to filter solution based on solution name, version, description like search.

---
- Deployment: Online
- DB Version: 9.2.21024.142
- Connection Controls Version: 1.2021.2.40
- XrmToolBox Version: 1.2021.2.45
- Tool Version: 1.2020.5.5

**Comment by MscrmTools** [comment]
Fixed in latest version to come shortly
