### ISSUE TITLE
Not moving over Custom API's, and their Request or Response Parameters,

### ISSUE THREAD

**Issue by DavidCrookEy** [MscrmTools/MsCrmTools.SolutionComponentsMover#16]
Version 1.2021.2.4 - I have a custom api and their parameters in a solution, they are checked in the options, but after the tool completes, the components are not found in the new solution.

**Comment by MscrmTools** [comment]
There is an updated version that handles these components. Please update the tool

**Comment by MscrmTools** [comment]
@DavidCrookEy, can you test with this version? I got a chat with Microsoft and they explained me a different way to handle the new components
[MsCrmTools.SolutionComponentsMover.zip](https://github.com/MscrmTools/MsCrmTools.SolutionComponentsMover/files/7205607/MsCrmTools.SolutionComponentsMover.zip)

**Comment by DavidCrookEy** [comment]
That fixes it. Thank you.
