### ISSUE TITLE
Uncheck "[Deprecated] Dynamics Customer Service Analytics" leads to error

### ISSUE THREAD

**Issue by d365User** [MscrmTools/MsCrmTools.SolutionComponentsMover#17]
![grafik](https://user-images.githubusercontent.com/91531405/135058848-6be0512b-6ce2-4854-877e-177047f5e519.png)

![grafik](https://user-images.githubusercontent.com/91531405/135058969-4b6908c3-0a5e-464c-a436-fea403065f6e.png)

**Comment by d365User** [comment]
When checked, there is still an error at the end of the move process:
![grafik](https://user-images.githubusercontent.com/91531405/135059171-d7057056-8856-426c-a9f3-b0926aac00be.png)

**Comment by MscrmTools** [comment]
@d365User, can you test with this version ?
[MsCrmTools.SolutionComponentsMover.zip](https://github.com/MscrmTools/MsCrmTools.SolutionComponentsMover/files/7243505/MsCrmTools.SolutionComponentsMover.zip)

**Comment by d365User** [comment]
Thank you @MscrmTools 
The new version is working without any issues.

**Comment by MscrmTools** [comment]
cool! I'm publishing it
