### ISSUE TITLE
solutioncomponentdefinition was not found in the MetaDataCache

### ISSUE THREAD

**Issue by killi3000** [MscrmTools/MsCrmTools.SolutionComponentsMover#18]
Hi
When trying to load solutions I get this error message:

_An error occured: The entity with a name = 'solutioncomponentdefinition' with namemapping = 'Logical' was not found in the MetaDataCache._

I cant find any info about this. Any idea what this might be?

I am running an on-prem v9.0

**Comment by MscrmTools** [comment]
@killi3000, damn it! this is a new entity only available online... I will try to filter out this entity from the code when onPrem

**Comment by MscrmTools** [comment]
@killi3000 Can you test with this version?
[MsCrmTools.SolutionComponentsMover.zip](https://github.com/MscrmTools/MsCrmTools.SolutionComponentsMover/files/7260830/MsCrmTools.SolutionComponentsMover.zip)

**Comment by killi3000** [comment]
Thanks for the quick reply! I will check it out and let you know:)

**Comment by killi3000** [comment]
It worked! Thanks!
