### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by polshgiant** [MscrmTools/MsCrmTools.SolutionComponentsMover#2]
When I run the tool choosing the option to move all components, and the tool encounters a solution component which does not exist, it throws the following error:

![image](https://cloud.githubusercontent.com/assets/1887185/21627055/e07c264c-d1da-11e6-8589-7442b7b78d40.png)

Unfortunately, the tool then seems to stop moving solution components when it encounters this error.  It would be really great if the tool:

-  Continued copying components after receiving the error (I am actually trying to work around an issue where my solution has remnant solution component in it that is preventing me from exporting, and if the tool would continue copying components past the error I could use it to effectively work around the remnant solution component)
- Had a log window underneath the two panes showing a basic summary (and details of errors)
- Had an option to remove all components from a solution (preferrably by type; for example, if I could tell the tool to remove all workflows from a solution or all entities)
- If the window that asks which component types you want to move unchecked all the checkboxes upon unchecking the All checkbox.  Currently, if I want to move only components of one type, I have to uncheck All, and then uncheck 15+ boxes.

**Comment by AshV** [comment]
Last point of uncheck all, I also feel need of the same, Let me make a PR with that improvement.

**Comment by MscrmTools** [comment]
It's a very old issue but I will work on it :)

**Comment by MscrmTools** [comment]
I did not implement the cleaning feature. bu tthe rest of the feature are implemented for next release
