### ISSUE TITLE
[BUG] Solution Components Mover doesn't Entity Keys

### ISSUE THREAD

**Issue by JgatesHS** [MscrmTools/MsCrmTools.SolutionComponentsMover#20]
**Describe the bug**
The solutions component mover doesn't copy table keys between solutions. 

componenttype:
14 - EntityKey

**To Reproduce**
Include all component types when copying between solutions, keys are not in target solution after copy. 

**Expected behavior**
Entity keys should be included when copying all component types from one solution to another and the source solution contains entity keys. 

**Desktop (please complete the following information):**
 - XrmToolbox Version -- 1.2021.9.52
 - Tool version -- 1.2021.9.12

**Comment by MscrmTools** [comment]
@JgatesHS I tested it with the same version you used and it worked
Can you double check?
