### ISSUE TITLE
Solution Component Mover does not move Connection References

### ISSUE THREAD

**Issue by gprof** [MscrmTools/MsCrmTools.SolutionComponentsMover#21]
**Describe the bug**
The Solution Component Mover does not move the Connection References which were recently introduced by Microsoft.

**To Reproduce**
- Create a new solution 
- Add a new Power Automate flow to a solution and make sure to also add the associated Connection Reference. 
- Then run the Solution Component Mover and move the new solution to another environment (e.g. Test)

**Expected behavior**
After the solution is copied to the selected enviroment both the new Power Automate flow and the associated Connection reference should be present.

**Screenshot**
![image](https://user-images.githubusercontent.com/25688152/116989444-0ad87680-acd2-11eb-9734-0be08d4dbbe2.png)

**Desktop (please complete the following information):**
 - XrmToolbox Version: 1.20.20.6.40
 - Tool version: 1.20.20.5

**Comment by MscrmTools** [comment]
Fixed in latest version
