### ISSUE TITLE
Allow moving power app components with in "Solution Components Mover" tool

### ISSUE THREAD

**Issue by nakhtar-ntg** [MscrmTools/MsCrmTools.SolutionComponentsMover#22]
Microsoft is moving towards maker.powerapps.com for solution management where you can add multiple components in the solution like power automate flows and their connections. There is a challenge that this tool has no option to move/merge the power platform components.

I am looking to add power platform components like flows, connector dlls, AI bot configurations, merge capability.

I am currently manually adding within the solution which is cumbersome for multiple solutions

**Comment by MscrmTools** [comment]
With latest version I succeeded to move connection references, flows, etc.

@nakhtar-ntg can you test if it works for you with other components?

**Comment by MscrmTools** [comment]
Closing the issue. Please reopen if you still have an issue
