### ISSUE TITLE
Move Components to another CRM instance

### ISSUE THREAD

**Issue by nakhtar-ntg** [MscrmTools/MsCrmTools.SolutionComponentsMover#23]
I would like a feature to be added so we can move the components from one environment to another.

**Comment by MscrmTools** [comment]
It is called solutions, isn't it?

**Comment by nakhtar-ntg** [comment]
> It is called solutions, isn't it?

What if we just need to move one component like a form, you need to add the entity that comes with the ribbon by default. On import the solution to another environment, the entity ribbon gets updated as well which we don't want. That's why I proposed this feature. 

By the way, your comment seems not friendly!

**Comment by MscrmTools** [comment]
Ok, so be more specific on your demand. 

99% of components can be moved individually with solutions.
Only entity subcomponents could be problematic, and this is just because of the ribbon you are mentioning.

In my opinion, that would be too much work for a so specific scenario.

**Comment by nakhtar-ntg** [comment]
Any subcomponent within the entity (not specific to the one I reported) has the same issue. In case there is no room space for improvement in this tool, I have no further comments.
