### ISSUE TITLE
Filter solutions by Managed/Unmanaged

### ISSUE THREAD

**Issue by rappen** [MscrmTools/MsCrmTools.SolutionComponentsMover#30]
At least to see the managed flag in the lists?

---
- Deployment: Online
- DB Version: 9.2.22123.194
- Connection Controls Version: 1.2022.10.54
- XrmToolBox Version: 1.2023.1.63
- Tool Version: 1.2021.9.12

**Comment by MscrmTools** [comment]
Adding the column

**Comment by MscrmTools** [comment]
released!

**Comment by rappen** [comment]
![CoolImGIF](https://user-images.githubusercontent.com/2572253/216082232-7040572c-5cee-4d07-816b-f72665ca26f2.gif)
