### ISSUE TITLE
Solution Components Mover option to prevent managed entities with rootcomponentbehavior=0

### ISSUE THREAD

**Issue by mattp65** [MscrmTools/MsCrmTools.SolutionComponentsMover#4]
It would be nice to have the option to prevent adding a Managed Entity to the target solution with "All Assets". Currently, this will override the target solution and update an existing entity (say Contact) to have rootcomponentbehavior=0 even if it was previoulsy in the target solution with bahviour 1 or 2. By default, this should not allow 0 on a managed entity. It should also prompt or throw an error beforce overriding the value in the target solution.

**Comment by MscrmTools** [comment]
ok, so I checked the code and the behavior is taken from the source solution. So I guess you would like a warning if source and target solution behavior are different, am I right?

**Comment by mattp65** [comment]
At a minimum, a warning would be great before overwriting the Target's rootcomponentbehavior. 

I think there is value in extending the warning to include adding any Managed entity with rootcomponentbehavior=0 since that violates best practice for establishing solutions that don't step on other changes.

**Comment by MscrmTools** [comment]
Ok, I will start with a warning when managed entities are added with behavior = 0

**Comment by MscrmTools** [comment]
released
