### ISSUE TITLE
Metadata 

### ISSUE THREAD

**Issue by dirkr1** [MscrmTools/MsCrmTools.SolutionComponentsMover#6]
When moving components from one solution to another, metadata is added to the copy. So moving components from the target to another solution won't work.

The metadata should be added as in the source solution defined.

I just tried to skip all metadata, then it worked for entities, but not for WebResources, OptionSets or Workflows.

**Comment by MscrmTools** [comment]
Not sure to understand what you mean by metadata here... can you precise?

**Comment by dirkr1** [comment]
Actually all solution components are added to the new solution with the AddSolutionComponentRequest. This request has optionally the parameter IncludedComponentSettingsValues.
Currently this parameter is omitted, so all entity metadata is added in the target solution (while it was not added in the source solution). I just tried to add the parameter IncludedComponentSettingsValues with an empty string arrray, but this fails when moving WebResources, OptionSets or Workflows. 
This should be dependant on the componenttype and on whether the source solution contains the metadata for this component.
Currently when you try to ove a managed entity (e.g. account with custom fields) from a custom solution 1 to solution 2, this works. After this when you try to move then from solution 2 to solution 3 it fails, because of violation of best practices.

**Comment by MscrmTools** [comment]
ok, that makes sense, I will review this

**Comment by MscrmTools** [comment]
Can you test this version of the tool? and tell me if it works better for you?

[MsCrmTools.SolutionComponentsMover.zip](https://github.com/MscrmTools/MsCrmTools.SolutionComponentsMover/files/4995442/MsCrmTools.SolutionComponentsMover.zip)
